"""Check the vendored wire schemas and compile them into a module.

`schema/*.json` arrives from Welt through Oide, so it is a copy rather than
the original: a truncated pull or a partial write would leave the adapter
validating against something that is not a schema at all. This reads each
one, refuses it unless it parses and is a valid 2020-12 schema, and writes
what it read into the package as `_schema.py`.

Compiling them in rather than reading them at run time keeps the schemas
where the package is, whatever the repository does with `schema/` — nothing
to include in the wheel, and no file that can go missing once installed.

Run it through `validate.sh`, which fails on the diff when the module and
the JSON have drifted apart.
"""

import json
import pathlib
import pprint

from jsonschema import Draft202012Validator

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "welt_io_strands" / "_schema.py"
SCHEMAS = (
    ("REQUEST_PAYLOAD", "request-payload"),
    ("REPLY_EVENTS", "reply-events"),
)
HEADER = '"""The wire schemas, generated by scripts/generate_schema.py."""'


def checked_schema(name: str) -> dict:
    """
    Read one vendored schema, refusing what is not one.

    Args:
        name (str): The schema's file name, without the suffix.

    Returns:
        dict: The schema.

    Raises:
        json.JSONDecodeError: If the file is not JSON.
        jsonschema.exceptions.SchemaError: If it is JSON but not a valid
            2020-12 schema.
    """
    schema = json.loads((ROOT / "schema" / f"{name}.schema.json").read_text())
    Draft202012Validator.check_schema(schema)
    return schema


def main() -> None:
    """
    Write the checked schemas into the package.

    Returns:
        None
    """
    parts = [HEADER]
    for constant, name in SCHEMAS:
        schema = checked_schema(name)
        parts.append(f"{constant}: dict = {pprint.pformat(schema, sort_dicts=False)}")
    OUTPUT.write_text("\n\n".join(parts) + "\n")


if __name__ == "__main__":
    main()
