name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-python.yml@873e99243e0ab9f834bb4eb42198f701bfe5c21c # v8.4.0
    with:
      python-versions: '["3.12","3.13","3.14"]'
