name: Compatibility

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-python.yml@cbf06d35d04e4ad85d157a5cda1484876d1a71f2 # v8.8.2
    with:
      python-versions: '["3.12","3.13","3.14"]'
